export const EXAMPLES = {
  "unmeasured-ion": {
    ph: "7.22",
    pco2: "25",
    hco3: "10",
    sbe: "-18",
    sodium: "140",
    chloride: "104",
    albumin: "40",
    lactate: "6",
    phosphate: "",
    pco2Unit: "mmHg",
    albuminUnit: "g/L",
    chronicHypercapnia: false,
  },
  hyperchloremic: {
    ph: "7.28",
    pco2: "30",
    hco3: "14",
    sbe: "-12",
    sodium: "140",
    chloride: "118",
    albumin: "40",
    lactate: "",
    phosphate: "",
    pco2Unit: "mmHg",
    albuminUnit: "g/L",
    chronicHypercapnia: false,
  },
  hypoalbuminemic: {
    ph: "7.46",
    pco2: "44",
    hco3: "30",
    sbe: "6",
    sodium: "140",
    chloride: "105",
    albumin: "20",
    lactate: "",
    phosphate: "",
    pco2Unit: "mmHg",
    albuminUnit: "g/L",
    chronicHypercapnia: false,
  },
  masked: {
    ph: "7.40",
    pco2: "40",
    hco3: "24",
    sbe: "0",
    sodium: "140",
    chloride: "111",
    albumin: "20",
    lactate: "",
    phosphate: "",
    pco2Unit: "mmHg",
    albuminUnit: "g/L",
    chronicHypercapnia: false,
  },
  "chronic-hypercapnia": {
    ph: "7.37",
    pco2: "60",
    hco3: "32",
    sbe: "8",
    sodium: "145",
    chloride: "103",
    albumin: "40",
    lactate: "",
    phosphate: "",
    pco2Unit: "mmHg",
    albuminUnit: "g/L",
    chronicHypercapnia: true,
  },
};
